name = "Crafthub III v2"
author = "リェンーゆく & TheClashFruit"
version = "1.3.1-ryenyuku+1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "898b0ec0888489f7acc78af38001bd7c1d51f55630f3c40e08b813af01331336"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
