name = "Crafthub III v2"
author = "リェンーゆく & TheClashFruit"
version = "1.3.1-ryenyuku+1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c847a61f1a11d5dd51d86cdd58ae06f16cbd5be732f337c74355ca8e5f9051f6"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
