name = "Crafthub III v2"
author = ["リェンーゆく", "TheClashFruit"]
version = "1.3.1+1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dc2a9068d88eba5a49a7b1a2db970b584be34eadeed45e57d0011ac0eb2e446"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
