name = "Crafthub III"
author = "リェンーゆく & TheClashFruit"
version = "1.4.0-ryenyuku+1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74177881c92e91f3286c7f8ff66dc88bd6e2897ee15e0e50dec02a4156f31f60"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
