name = "Crafthub III v2"
author = "リェンーゆく & TheClashFruit"
version = "1.3.1-ryenyuku+1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77239c09c5f8f79966daa3010dc240003ba24360014c8da94e97c1b727449adc"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
